plugins {
    id 'nva.cristin.service.core.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.core)
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.apigateway)
    api(nvaLibs.core)
    api(nvaLibs.json)
    api(project(":cristin-commons"))
    implementation(libs.bekkopen.nocommons)
    implementation(nvaCatalog.httpcore5)
    implementation(nvaCatalog.slf4j.api)
    testImplementation(libs.json.assert)
    testImplementation(libs.karate.core)
    testImplementation(libs.karate.junit5)
    testImplementation(nvaCatalog.assertj.core)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaCatalog.log4j.core)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaCatalog.zalando)
    testImplementation(nvaLibs.logutils)
    testImplementation(nvaLibs.testutils)
    testImplementation(project(":cristin-testing"))
    testRuntimeOnly(nvaCatalog.junit.jupiter.engine)
}

tasks.named('test', Test) {
    useJUnitPlatform {
        excludeTags 'karateTest', 'integrationTest'
    }
}

test {
    environment "COGNITO_AUTHORIZER_URLS", "http://localhost:3000"
}
