plugins {
    id 'nva.java-conventions'
    id 'java-test-fixtures'
}

nva {
    pmd {
        rulesetFile = rootProject.file('config/pmd/ruleset.xml')
    }
}

dependencies {
    implementation(platform("software.amazon.awssdk:bom:${nvaCatalog.versions.aws.sdk2.asProvider().get()}"))
    testFixturesImplementation(platform("software.amazon.awssdk:bom:${nvaCatalog.versions.aws.sdk2.asProvider().get()}"))
}

tasks.named('test', Test) {
    environment "ALLOWED_ORIGIN", "*"
    environment "CRISTIN_API_URL", "https://api.cristin-test.uio.no/v2"
    environment "BASE_PATH", "cristin"
    environment "DOMAIN_NAME", "api.dev.nva.aws.unit.no"
    environment "COGNITO_URI", "https://example.cognito.org"
    environment "CRISTIN_BOT_FILTER_BYPASS_HEADER_NAME", "Hello"
    environment "CRISTIN_BOT_FILTER_BYPASS_HEADER_VALUE", "World"
}

tasks.register('createTestUsers', Test) {
    useJUnitPlatform {
        includeTags('createTestUsers')
    }

    outputs.upToDateWhen { false }
}

tasks.register('deleteTestUsers', Test) {
    useJUnitPlatform {
        includeTags('deleteTestUsers')
    }

    outputs.upToDateWhen { false }
}

tasks.register('karateTest', Test) {
    useJUnitPlatform {
        includeTags('karateTest')
    }

    environment "ALLOWED_ORIGIN", "*"
    environment "CRISTIN_API_URL", "https://api.cristin-test.uio.no/v2"
    environment "DOMAIN_NAME", "api.dev.nva.aws.unit.no"

    systemProperty "karate.options", System.properties.getProperty("karate.options")
    systemProperty "karate.env", System.properties.getProperty("karate.env")
    outputs.upToDateWhen { false }
}
