plugins {
    id 'nva.root-module-conventions'
}

nva {
    dependencyAnalysis {
        enforced = false
    }
    jacoco {
        // FIXME: Remove dead code and add tests for remaining gaps (see NP-49448)
        minMethodCoverage = new BigDecimal('0.888')
        minClassCoverage = new BigDecimal('0.963')
    }
    spectral {
        documents = ['docs/*.yaml']
        rulesetFile = file('.spectral.yaml')
    }
}
