version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "karate-cristin-service-np3360"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-plnc75nq3gkx"
s3_prefix = "karate-cristin-service-np3360"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CustomDomain=\"api.dev.nva.aws.unit.no\" CustomDomainBasePath=\"cristin-karate-np3360\" CristinApiHost=\"api.cristin.no\""
image_repositories = []
