version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-likdhaef7wvo"
s3_prefix = "karate-cristin-service-temp"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
