version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "np3360-karate-cristin-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p5lpypja4afp"
s3_prefix = "np3360-karate-cristin-service"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CustomDomain=\"api.dev.nva.aws.unit.no\" CustomDomainBasePath=\"cristin-np3360\" CristinApiHost=\"api.cristin.no\""
image_repositories = []
