AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template creates lambda, api-gateway and custom domain mapping for fetching project data


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Architectures:
      - arm64
    Environment:
      Variables:
        ALLOWED_ORIGIN: '*'
        CRISTIN_API_HOST: !Ref CristinApiHost
        DOMAIN_NAME: !Ref CustomDomain
        BASE_PATH: !Ref CustomDomainBasePath
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'OPTIONS, GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, Access-Control-Allow-Origin'"

Parameters:
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
    Default: 'api.dev.nva.aws.unit.no'
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: 'cristin'
  CristinApiHost:
    Type: String
    Description: Hostname for Cristin API
    Default: 'api.cristin.no'

Resources:

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  NvaCristinProxyApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/cristin-proxy-swagger.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      Auth:
        DefaultAuthorizer: NONE
      EndpointConfiguration: Regional


  NvaCristinProjectsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cristin-project
      Handler: no.unit.nva.cristin.projects.FetchCristinProjects::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinProjectsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /project/
            Method: get
            RequestParameters:
              - method.request.querystring.language
              - method.request.querystring.query
              - method.request.querystring.page
              - method.request.querystring.results

  NvaCristinOneProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-project
      Handler: no.unit.nva.cristin.projects.FetchOneCristinProject::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOneProjectEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /project/{id}
            Method: get
            RequestParameters:
              - method.request.querystring.language

  NvaCristinQueryOrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-organization
      Handler: no.unit.nva.cristin.organization.QueryCristinOrganization::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOrganizationsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /organization/
            Method: get
            RequestParameters:
              - method.request.querystring.query
              - method.request.querystring.page
              - method.request.querystring.results

  NvaCristinGetOrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-project
      Handler: no.unit.nva.cristin.organization.FetchCristinOrganization::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOneProjectEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /organization/{id}
            Method: get

  NvaCristinProjectsFunctionBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref NvaCristinProxyApi
      Stage: !Ref NvaCristinProxyApi.Stage
