AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template creates lambda, api-gateway and custom domain mapping for fetching project data


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 40
    Architectures:
      - arm64
    Environment:
      Variables:
        ALLOWED_ORIGIN: '*'
        CRISTIN_API_URL: !Ref CristinApiUrl
        DOMAIN_NAME: !Ref ApiDomain
        BASE_PATH: !Ref CustomDomainBasePath
        COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId

  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'OPTIONS, GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, Access-Control-Allow-Origin'"

Parameters:
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  ApiDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/ApiDomain
    Description: Domain-name for the backend
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: 'cristin'
  CristinApiUrl:
    Type: String
    Description: Url for Cristin API
    Default: https://api.cristin-test.uio.no/v2
    AllowedValues:
      - https://api.cristin-test.uio.no/v2
      - https://api.cristin.no/v2
  CognitoUserPoolId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoUserPoolId

Resources:

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  NvaCristinProxyApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/cristin-proxy-swagger.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      Auth:
        DefaultAuthorizer: NONE
      EndpointConfiguration: Regional

  NvaCristinProxyInternalApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/cristin-proxy-internal-apidoc.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod

      EndpointConfiguration: Regional


  ReadCristinAuthenticationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: readSecret
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:CristinClientBasicAuth*'


  NvaCristinProjectsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cristin-project
      Handler: no.unit.nva.cristin.projects.FetchCristinProjects::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinProjectsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /project/
            Method: get
            RequestParameters:
              - method.request.querystring.query
              - method.request.querystring.page
              - method.request.querystring.results

  NvaCristinCreateProjectsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cristin-project
      Handler: no.unit.nva.cristin.projects.CreateCristinProjectHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinProjectsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /project/
            Method: post

  NvaCristinOneProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-project
      Handler: no.unit.nva.cristin.projects.FetchOneCristinProject::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinOneProjectEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /project/{id}
            Method: get

  NvaCristinQueryOrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-organization
      Handler: no.unit.nva.cristin.organization.QueryCristinOrganizationHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOrganizationsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /organization/
            Method: get
            RequestParameters:
              - method.request.querystring.query
              - method.request.querystring.page
              - method.request.querystring.results

  NvaCristinFetchOrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-organization
      Handler: no.unit.nva.cristin.organization.FetchCristinOrganizationHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOneProjectEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /organization/{id}
            Method: get

  NvaCristinQueryPersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.handler.QueryCristinPersonHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinQueryPersonEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/
            Method: get
            RequestParameters:
              - method.request.querystring.query
              - method.request.querystring.page
              - method.request.querystring.results

  NvaCristinFetchPersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.handler.FetchCristinPersonHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinFetchPersonEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/{id}
            Method: get

  NvaCristinFetchPersonUsingNinFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.handler.FetchFromIdentityNumberHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinFetchPersonUsingNinEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/identityNumber/
            Method: post
        NvaCristinFetchPersonUsingInternalRequest:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyInternalApi
            Path: /person/identityNumber/
            Method: post

  NvaCristinCreatePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.create.CreateCristinPersonHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinCreatePersonEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/
            Method: post

  NvaCristinUpdatePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.update.UpdateCristinPersonHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      #Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinUpdatePersonEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/{id}/
            Method: patch

  NvaCristinFetchPersonInstitutionInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.institution.fetch.FetchPersonInstitutionInfoHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinFetchPersonEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/{id}/organization/{orgId}/
            Method: get

  NvaCristinUpdatePersonInstitutionInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.institution.update.UpdatePersonInstitutionInfoHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinUpdatePersonInstitutionInfoEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/{id}/organization/{orgId}/
            Method: patch

  NvaCristinFetchPositionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.affiliations.handler.PositionCodesHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinFetchPositionsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /position/
            Method: get

  NvaCristinQueryPersonEmploymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.employment.query.QueryPersonEmploymentHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt ReadCristinAuthenticationRole.Arn
      Events:
        NvaCristinQueryPersonEmploymentEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/{id}/employment/
            Method: get

  NvaCristinProxyBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref ApiDomain
      RestApiId: !Ref NvaCristinProxyApi
      Stage: !Ref NvaCristinProxyApi.Stage

  InternalBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Sub '${CustomDomainBasePath}-internal'
      DomainName: !Ref ApiDomain
      RestApiId:  !Ref NvaCristinProxyInternalApi
      Stage: !Ref NvaCristinProxyInternalApi.Stage



