AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template creates lambda, api-gateway and custom domain mapping for fetching project data


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 40
    Architectures:
      - arm64
    Environment:
      Variables:
        ALLOWED_ORIGIN: '*'
        CRISTIN_API_URL: !Ref CristinApiUrl
        DOMAIN_NAME: !Ref ApiDomain
        BASE_PATH: !Ref CustomDomainBasePath
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'OPTIONS, GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, Access-Control-Allow-Origin'"

Parameters:
  ApiDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/ApiDomain
    Description: Domain-name for the backend
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: 'cristin'
  CristinApiUrl:
    Type: String
    Description: Url for Cristin API
    Default: https://api.cristin-test.uio.no/v2
    AllowedValues:
      - https://api.cristin-test.uio.no/v2
      - https://api.cristin.no/v2
Resources:

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  NvaCristinProxyApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/cristin-proxy-swagger.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      Auth:
        DefaultAuthorizer: NONE
      EndpointConfiguration: Regional


  NvaCristinProjectsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cristin-project
      Handler: no.unit.nva.cristin.projects.FetchCristinProjects::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinProjectsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /project/
            Method: get
            RequestParameters:
              - method.request.querystring.query
              - method.request.querystring.page
              - method.request.querystring.results

  NvaCristinOneProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-project
      Handler: no.unit.nva.cristin.projects.FetchOneCristinProject::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOneProjectEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /project/{id}
            Method: get

  NvaCristinQueryOrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-organization
      Handler: no.unit.nva.cristin.organization.QueryCristinOrganizationHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOrganizationsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /organization/
            Method: get
            RequestParameters:
              - method.request.querystring.query
              - method.request.querystring.page
              - method.request.querystring.results

  NvaCristinFetchOrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-organization
      Handler: no.unit.nva.cristin.organization.FetchCristinOrganizationHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOneProjectEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /organization/{id}
            Method: get

  NvaCristinQueryPersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.handler.QueryCristinPersonHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinQueryPersonEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/
            Method: get
            RequestParameters:
              - method.request.querystring.query
              - method.request.querystring.page
              - method.request.querystring.results

  NvaCristinFetchPersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cristin-person
      Handler: no.unit.nva.cristin.person.handler.FetchCristinPersonHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinFetchPersonEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NvaCristinProxyApi
            Path: /person/{id}
            Method: get

  NvaCristinProxyBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref ApiDomain
      RestApiId: !Ref NvaCristinProxyApi
      Stage: !Ref NvaCristinProxyApi.Stage

