[versions]
junit = {strictly = '5.8.2'}
nva-commons = {strictly = '1.16.30'}
jackson = {strictly = '2.13.0'}
mockito = {strictly = '4.1.0'}
hamcrest = {strictly = '2.2'}
zalando = {strictly = '0.26.0'}
javax-ws-rs = {strictly = '2.1.1'}
jsoup = {strictly = '1.14.3'}
aws-lambda-java-core = {strictly = '1.2.1'}
google-guava = {strictly = '31.0.1-jre'}
karate-core = {strictly = '1.1.0'}
karate-apache = {strictly = '0.9.6'}
karate-junit5 = {strictly = '1.1.0'}
log4jApi = { strictly = '2.17.1' }
slf4j = { strictly = '1.8.0-beta4' }
nva-language = { strictly = '1.0' }
awsSdk = { strictly = '1.12.129' }
bekkopen-nocommons = { strictly = '0.12.0' }
[libraries]

#Test

junit-jupiter-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'junit' }
junit-jupiter-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'junit' }
junit-jupiter-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'junit' }

mockito-core = { group = 'org.mockito', name = 'mockito-core', version.ref = 'mockito' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version.ref = 'hamcrest' }
nva-testutils = { group = 'com.github.bibsysdev', name = 'nvatestutils', version.ref = 'nva-commons' }
nva-logutils = { group = 'com.github.bibsysdev', name = 'logutils', version.ref = 'nva-commons' }
zalando = { group = 'org.zalando', name = 'problem', version.ref = 'zalando' }
karate-core = { group = 'com.intuit.karate', name = 'karate-core', version.ref = 'karate-core'}
karate-apache = { group = 'com.intuit.karate', name = 'karate-apache', version.ref = 'karate-apache'}
karate-junit5 = { group = 'com.intuit.karate', name = 'karate-junit5', version.ref = 'karate-junit5'}
karate-parent = { group = 'com.intuit.karate', name =  'karate-parent', version.ref = 'karate-core'}

#Regular

nva-commons-core = { group = 'com.github.bibsysdev', name = 'core', version.ref = 'nva-commons' }
nva-commons-apigateway = { group = 'com.github.bibsysdev', name = 'apigateway', version.ref = 'nva-commons' }
nva-language = { group = 'com.github.bibsysdev', name = 'nva-language', version.ref = 'nva-language' }
nva-secrets = { group = "com.github.bibsysdev", name = "secrets", version.ref = "nva-commons" }
nva-lambdaauthorizer = { group = 'com.github.bibsysdev', name = 'lambdaauthorizer', version.ref = 'nva-commons' }

jackson-core = { group = 'com.fasterxml.jackson.core', name = 'jackson-core', version.ref = 'jackson' }
jackson-databind = { group = 'com.fasterxml.jackson.core', name = 'jackson-databind', version.ref = 'jackson' }
jackson-annotations = { group = 'com.fasterxml.jackson.core', name = 'jackson-annotations', version.ref = 'jackson' }
jackson-datatype-jdk8 = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jdk8', version.ref = 'jackson' }
jackson-datatype-jsr310 = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jsr310', version.ref = 'jackson' }

javax-ws-rs = { group = 'javax.ws.rs', name = 'javax.ws.rs-api', version.ref = 'javax-ws-rs' }
jsoup = { group = 'org.jsoup', name = 'jsoup', version.ref = 'jsoup' }
aws-lambda-java-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'aws-lambda-java-core' }
google-guava = { group = 'com.google.guava', name = 'guava', version.ref = 'google-guava' }

aws-sdk-core = { group = 'com.amazonaws', name = 'aws-java-sdk-core', version.ref = 'awsSdk' }
aws-sdk-secrets = { group = 'com.amazonaws', name = 'aws-java-sdk-secretsmanager', version.ref = 'awsSdk' }
aws-sdk-cognitoidp = { group ='com.amazonaws', name = 'aws-java-sdk-cognitoidp', version.ref ='awsSdk' }

log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4jApi' }
slf4j-api = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j' }

bekkopen-nocommons = { group = 'no.bekk.bekkopen', name =  'nocommons', version.ref =  'bekkopen-nocommons' }

[bundles]
nvaCommons = ['nva-commons-core', 'nva-commons-apigateway']
testing = ['junit-jupiter-api', 'junit-jupiter-params', 'junit-jupiter-engine', 'mockito-core', 'hamcrest', 'nva-testutils', 'nva-logutils', 'zalando']
jackson = ['jackson-core', 'jackson-databind', 'jackson-annotations', 'jackson-datatype-jdk8', 'jackson-datatype-jsr310']
others = ['javax-ws-rs', 'slf4j-api', 'log4j-api', 'jsoup', 'aws-lambda-java-core', 'google-guava']
