name: Connect-to-AWS
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::884807050265:role/GithubActionsRole
          aws-region: eu-west-1
      - run: aws sts get-caller-identity # just an example. why not deploy something?
