name: Connect-to-AWS
on:
  push:

jobs:
  deploy:
    name: Connect to Amazon
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::884807050265:role/nva-dev-github-actions-role
          aws-region: eu-west-1
      - run: aws sts get-caller-identity # just an example. why not deploy something?
