name: Karate API tests

on: [push]
env:
  STACK_NAME: karate-cristin-np3471
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::884807050265:role/nva-dev-github-actions-role
          aws-region: eu-west-1
      - name: Build and deploy
        - run: Echo building $GITHUB_REPOSITORY $GITHUB_REF_NAME
        -  run: sam build
      # Prevent prompts and failure when the stack is unchanged
        - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset  --stack-name $STACK_NAME --parameter_overrides = "CustomDomain=\"api.dev.nva.aws.unit.no\" CustomDomainBasePath=\"cristin-karate-np3471\" CristinApiHost=\"api.cristin.no\""
      # Run karate tests on deployed api
      - name: Run Karate tests erikbos/karate-action@main
        uses: erikbos/karate-action@main
        with:
          url: https://api.dev.nva.aws.unit.no/np3392-karate-cristin/
          tests: |
            cristin-organization/src/test/java/no/unit/nva/cristin/organization/organization.feature
            cristin-project/src/test/java/no/unit/nva/cristin/projects/project.feature
      # Delete stack after running tests
      - run: sam delete --no-prompts
