name: Karate API tests

on: [ push ]
env:
  STACK_NAME: cristin-$GITHUB_REF_NAME
  BASE_PATH: cristin-$GITHUB_REF_NAME
  DOMAIN_NAME:  "api.dev.nva.aws.unit.no"
  CRISTIN_API: "api.cristin.no"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::884807050265:role/nva-dev-github-actions-role
          aws-region: eu-west-1
      - name: Build
        run: sam build
      # Prevent prompts and failure when the stack is unchanged
      - name: Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset  --stack-name ${{env.STACK_NAME}} --parameter-overrides ParameterKey=CustomDomain,ParameterValue=${DOMAIN_NAME} ParameterKey=CustomDomainBasePath,ParameterValue=${{env.BASE_PATH}} ParameterKey=CristinApiHost,ParameterValue=${CRISTIN_API}
      # Take a break waiting for API to deploy
      - name: Sleep for 30 seconds
        run: sleep 30s
      # Run karate tests on deployed api
      - name: Run karate tests with Gradle
        run: BASE_PATH=${{env.BASE_PATH}} ./gradlew karateTest -x test --info
      # Delete stack after running tests
      - name: Delete stack after running tests
        run: sam delete --no-prompts --region eu-west-1 --stack-name ${{env.STACK_NAME}}
