name: Karate API tests

on: [ push ]
env:
  STACK_NAME: "karate-cristin-np3471"
  BASE_PATH: "cristin-karate-tests"
  ANOTHER_BASE_PATH: "cristin-karate-tests-${GITHUB_REF_NAME}"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::884807050265:role/nva-dev-github-actions-role
          aws-region: eu-west-1
      - name: Echo environment
        run: echo building ${GITHUB_REPOSITORY} ${GITHUB_REF_NAME} ${STACK_NAME} ${BASE_PATH} ${ANOTHER_BASE_PATH}
      - name: Build
        run: sam build
      #       Prevent prompts and failure when the stack is unchanged
      - name: Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset  --stack-name ${STACK_NAME} --parameter-overrides ParameterKey=CustomDomain,ParameterValue=api.dev.nva.aws.unit.no ParameterKey=CustomDomainBasePath,ParameterValue=${BASE_PATH} ParameterKey=CristinApiHost,ParameterValue=api.cristin.no
#       Run karate tests on deployed api
      - name: Run karate tests with Gradle
        run: ./gradlew karateTest -x test
#      Delete stack after running tests
      - name: Delete stack after running tests
        run: sam delete --no-prompts --stack-name ${STACK_NAME}
