plugins {
    id 'nva.cristin.service.core.java-conventions'
}

dependencies {
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.core)
    api(nvaCatalog.jackson.databind)
    api(nvaCatalog.resilience4j.retry)
    api(nvaCatalog.slf4j.api)
    api(nvaLibs.apigateway)
    api(nvaLibs.core)
    api(nvaLibs.json)
    api(nvaLibs.secrets)
    implementation(nvaCatalog.httpcore5)
    implementation(nvaCatalog.nva.language)
    implementation(nvaCatalog.vavr)
    testFixturesImplementation('software.amazon.awssdk:auth')
    testFixturesImplementation('software.amazon.awssdk:aws-core')
    testFixturesImplementation('software.amazon.awssdk:cognitoidentityprovider')
    testFixturesImplementation('software.amazon.awssdk:http-client-spi')
    testFixturesImplementation('software.amazon.awssdk:regions')
    testFixturesImplementation('software.amazon.awssdk:url-connection-client')
    testFixturesImplementation(nvaCatalog.aws.sdk2.core)
    testFixturesImplementation(nvaCatalog.jackson.databind)
    testFixturesImplementation(nvaLibs.apigateway)
    testFixturesImplementation(nvaLibs.core)
    testFixturesImplementation(nvaLibs.json)
    testImplementation(nvaCatalog.assertj.core)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaCatalog.log4j.core)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaLibs.logutils)
    testImplementation(nvaLibs.testutils)
    testRuntimeOnly(nvaCatalog.junit.jupiter.engine)
}

tasks.named('test', Test) {
    useJUnitPlatform {
        excludeTags 'karateTest', 'integrationTest', 'createTestUsers', 'deleteTestUsers'
    }
}
